### ISSUE TITLE
Volume not changed with slider as expected.

### ISSUE THREAD

**Issue by thexperiments** [mwittig/pimatic-denon-avr#10]
I have this for some time now but didn't find the time to report it yet.

Currently if I try to change the volume via the slider in the Pimatic web frontend the moment I let it go it jumps back to previous value or even decreases. Only after several tries I get it to increase a little bit.

**Comment by mwittig** [comment]
That's normal behaviour.  You cannot change the volume (or any other setting) when the receiver is not powered on. Alternatively, I can switch on the receiver when the volume is changes (similar to what happends if you change the input source).

**Comment by thexperiments** [comment]
But this happens if the receiver is switched on already. 
I think turning on when receiving a command when the receiver is of is a good idea in general.

**Comment by mwittig** [comment]
Hope this issue has been sorted with the latest release. Please re-open this ticket if the slider is still jumping in your setup. 

If you like this plugin, please consider &#x2605; starring [the project on github](https://github.com/mwittig/pimatic-denon-avr).
