### ISSUE TITLE
Add HTTP transport

### ISSUE THREAD

**Issue by thexperiments** [mwittig/pimatic-denon-avr#11]
Currently you can't use the plugin together with other apps as the "telnet/serial" communication only allows one client. Would be great if this can be changed. I know it is on the agenda but I wonder what the current status is.

**Comment by mwittig** [comment]
Well, if the other apps are "well behaved" and close the connection after the conversation has been completed, it works. I have two pimatic instances with the denon plugin and this works very well most of the time. However, adding the http transport also is a top-priority for me and I have already pulled together the necessary docs.

**Comment by thexperiments** [comment]
Great to hear! I don't have problems often so it is not to urgent

**Comment by mwittig** [comment]
Implemented and Released. If you like this plugin, please consider &#x2605; starring [the project on github](https://github.com/mwittig/pimatic-denon-avr).
