### ISSUE TITLE
Video signal is interrupted by changing volume

### ISSUE THREAD

**Issue by FWillems** [mwittig/pimatic-denon-avr#16]
If i change the volume by the slider of the device DenonAvrMasterVolume i get a annoing behavior of the plugin, the video signal is swiched off so that the screen is getting black and on again while displaying MAIN ZONE on.  Is that a bug or perhaps a behavior which could be enhanced/fixed?

I'm using the PlugIn with the Protocol TELNET on Port 23 and a Denon AVR-X3100W as hardware.

**Comment by mwittig** [comment]
I am using the plugin with a Denon AVR-X1200W and don't have such issues. What kind of video source are you using? Does it involve some video processing like A/D conversion or upscaling? Generally, I think the video processing is done by dedicated processor which is separate from the control system.

A few things you may want to try:

1) Make sure you have the current AVR firmware installed
2) Do you have enable the transmission of "anonymized usage data"? If yes, de-activate it.
3) Unplug the receiver for at least 10 seconds. This should restart the control system of the AVR
4) Switch the plugin to using the HTTP protocol, your AVR should support this

Please keep me posted about your findings

**Comment by mwittig** [comment]
@FWillems Any news on this from your side?

**Comment by FWillems** [comment]
Sorry for my delayed response. But at least all all your help hasn't solved the problem for me.

- I'm using a signal from a set top box (Vodafone TV Center) connected to the SAT input of my Denon AVR which is connected via HDMI (ARC-Channel) to my Samsung TV
- I'm not sure about the video upscaling but the I/P & Scaler option is set to off
_HDMI-Signal-Info
  Auflösung	1080i > 1080i_ 

To all other questions:

1. I had a firmware update some weeks ago to Version 1600-0161-6094. But before I also used pimatic 0.8 and with that everything was working fine.
2. Data transmission is set to off
3. I also did a restart wihtout changing anything
4. And also the Plugins is neither working correctly with TELNET nor with HTTP

I also have recognised that the volume is also not changing. When changing the volume by the slider the video signal is swiched shortly off and on again and alos to the volume is reseted to the volume before. So there is no vomlume change possible at least.
==> Instead the Input Selector is working fine!

Perhaps you have any other possibilities to fix the problem. Thank you for your help.

**Comment by mwittig** [comment]
Did you migrate to pimatic 0.9 **after** the firmware update to Version 1600-0161-6094? I am just trying to understand whether or not the issue may be related to the firmware update.

EDIT: It'll be nice if you can also lookup the firmware release notes/change log to see if there is any useful information. I can't do that as the serial no for the device is required

http://denon-uk.custhelp.com/app/answers/detail/a_id/956/~/firmware-update-release-notes

EDIT2: I had a report from another user who said video transmission is interrupted in his case when Zone 2 is turned on (even happends if you the remote or the receiver dial). He also said that increasing the volume via pimatic **DenonAvrMasterVolume** will turn on zone 2 and it will cause interruption in his case. Can you please try  to use the DenonAvrZoneVolume (configured to zone MAIN)  instead? Thanks! I'll will review recent changes to the volume control why zone 2 is turned on.

**Comment by FWillems** [comment]
I can't tell you if it has something to do with the Denon update or the pimatic update because my pimatic wasn't running for serveral days when i did the update to 0.9 and during this time the Denon has been updated.

So you're right, the DenonAvrZoneVolume Device with the configuration of Main zone is working perfect without any problems!

But to solve the Problem in general i can share the changelog of my Denon with you if you're interested in it anymore. By now, i do want to overload my comment by pasting the long changlog here.

**Comment by mwittig** [comment]
Thank you very much for your feedback.  

I have reviewed recent code changes. As part of version 0.9.1 of the plugin, I had changed **DenonAvrMasterVolume ** to automatically switch on the receiver (PWON command).  The PWON command is always sent and the AVR should ignore it if already switched on (this is known to work flawlessly with various AVR models). However, as you said, the plugin used to work fine for you in the past with pimatic 0.8. Moreover, the zone volume is working fine for you which does not send the PWON command. I think the PWON may be the causing the trouble.  I will change  the code for **DenonAvrMasterVolume **  accordingly on  the master branch. If you can test it when ready this will be great. I will get back to you with further instructions when available.

**Comment by FWillems** [comment]
For sure i'll try to help. Thank you for helping me out to get it working.

**Comment by mwittig** [comment]
Sorry for the delay in reply as I had been off for couple of days. 

I have changed the behavior of the master volume device and the issue should be fixed now. Please re-open if the issue still occurs

**Comment by mwittig** [comment]
Did you try the DenonAvrMasterVolume device with the latest version? Does it solve the problem? 

If you like this plugin, please consider &#x2605; starring [the project on github](https://github.com/mwittig/pimatic-denon-avr).

**Comment by mwittig** [comment]
No feedback. Asumming the issue has been resolved
