### ISSUE TITLE
DenonAvrInputSelector can't be changed via rules?

### ISSUE THREAD

**Issue by mkremeyer** [mwittig/pimatic-denon-avr#18]
Not sure if I'm doing anything wrong, but it seems like I can't select the DenonAvrInputSelector when creating a new rule. Master-volume, mute, and power are available in rules, but the input selector is not available. Is this a bug? Or is there a known workaround?

Use case: I use a dummy switch that's turned on/off via my amazon echo. Once it changes its state, I'd like to turn on the AV receiver (works) and 5 seconds later I'd like to switch the input to Bluetooth so I can connect my echo and play music.

**Comment by mwittig** [comment]
This has not been implemented yet and I have marked it an enhancement. I hope I'll be able to get to this soon.

**Comment by mwittig** [comment]
Released. If you like this plugin, please consider &#x2605; starring [the project on github](https://github.com/mwittig/pimatic-denon-avr). Thanks

**Comment by mkremeyer** [comment]
Saw it yesterday. Awesome, thanks! It's carnival right now but I hope to
find time next weekend :)
