### ISSUE TITLE
Can't set volume of Zone/Main via rules

### ISSUE THREAD

**Issue by thexperiments** [mwittig/pimatic-denon-avr#20]
I have not found a way to do this and thus volume can only be changed via GUI and not via rules

**Comment by mwittig** [comment]
You can use the *dim* action for all volume controls. I'll add this as a note to the README. The dim action takes a percentage value, e.g.

```
WHEN state of denon-avr-power is equal to on 
THEN avr input denon-avr-input-selector to "tuner" and dim denon-avr-master-volume to 50
```

If you like this plugin, please consider &#x2605; starring [the project on github](https://github.com/mwittig/pimatic-denon-avr). Thanks
