### ISSUE TITLE
Interval step change

### ISSUE THREAD

**Issue by p4co86** [mwittig/pimatic-denon-avr#21]
Hello Marcus,
is it possible to change the minimum interval to maybe 1 second or 2 seconds? actually i need a smaller step size.

Thanks in Advance

**Comment by mwittig** [comment]
It is possible and I am happy to lower it to 2 seconds, but it will cause a lot of traffic as each device requests updates individually.  To mitigate this a centralized update loop is desirable where each device can subscribe to the update topics in question (e.g. query the volume level) and the update handler can provide optimized queries which result in less callouts to the receiver. #22

**Comment by p4co86** [comment]
for the first i need it just for the sensor part. when i click the remote (Tv Audio) and the status in the pimatic device change to tv, then pimatic should switch the tv from av to tv, but actually it needs too much time because the interval is actually 10s. 

today i will try to change it in the source coude and make npm install.

**Comment by mwittig** [comment]
I have tested this with a 2 seconds interval. It seriosly degrades degrade the performance of the AVR control service. You'll notice that if you use the AVR web application or the Smartphone App. Please report back on your findings. Thanks

**Comment by mwittig** [comment]
@p4co86 Any news about your findings?

**Comment by p4co86** [comment]
Have changed the interval to 3, but i get now a high cpu. Maybe i change from RPI1 to RPI3.

**Comment by mwittig** [comment]
Do you use HTTP or TELNET? 
For HTTP I already had implemented an optimized update loop which is part of the release.

**Comment by p4co86** [comment]
i use telnet, i have a AVR-x2300, i have tried http but can not get it working. do i have to set a port or is it just not supported for my model ?

EDIT: Http Works, when did you plan the update for http interval

**Comment by mwittig** [comment]
Released as pimatic-denon-avr@0.9.7

If you like this plugin, please consider &#x2605; starring [the project on github](https://github.com/mwittig/pimatic-denon-avr). Thanks!
