### ISSUE TITLE
Source change for both zones

### ISSUE THREAD

**Issue by thexperiments** [mwittig/pimatic-denon-avr#8]
Would be great if this could be integrated that's the biggest thing I'm currently missing.

Most of the information should be here:
https://forum.pimatic.org/topic/979/denon-marantz-avr-remote-control

**Comment by mwittig** [comment]
I am not sure what you would like to have exactly. Do you want to have all the controls shown in the first post? That doable, but it'll be helpful if you can prioritize features.

Another thing I have on my list is to support HTTP Transport. The plugin currently uses telnet which is working fine, but the receive only accepts a single connection. This is a bit of a problem if you have multiple pimatic instances using it, eventhough the plugin does not keep the connection opened permanently.

**Comment by thexperiments** [comment]
Oh ok, didn't look into the sources yet, thought it already was using HTTP.

Priority 1 for me is changing the source for zone1 and zone 2 in order to realize rules like:

if Watch TV is pressed turn on TV and turn on Sat Receiver and turn on AVR and set AVR source2 to SAT/CBL and turn off Livingroom Light

**Comment by mwittig** [comment]
Ok, thanks. The reason why I have implemented this telnet-thingy is, that it is supported by all networked Denon & Marantz receivers (and it could also be accessed via serial line on even older receivers :) HTTP is only by the more recent models as far as I can tell.

**Comment by thexperiments** [comment]
Sure makes sense, I am currently controlling an Marantz SR6008 with your plugin and it works fine. I'm only using one pimatic instance and if the integration works good I think I also won't use the remote app on the smartphone anymore. I don't know if the SR6008 supports the HTTP transport already?

**Comment by mwittig** [comment]
Just wanted to let you know I started working on the matter. I have added a new device class "DenonAvrInputSelector" to master (not yet released to npm). I also need to investigate how to manage zones as I have used that yet.

**Comment by thexperiments** [comment]
Good to know. I also started with putting the collection of ruels/pseudo devices for control via http on the forum into a plugin but this might take some time as I am currently very busy.

**Comment by mwittig** [comment]
I have a good picture now on how the control protocol works for zoning. I'll extend the existing device types (power switch, mute switch, input selector) with a zone property to choose from main (default), z2 and z3. Same with volume basically, however, the device is call "master volume" right now, so I'll probably alias it for clarity.

**Comment by mwittig** [comment]
Implementation work done. Per zone, you can now switch on/off, change volume, mute, and select input. I'll do some more testing and will release on saturday. Next iteration will be do implement the http transport. My idea, is to let the plugin autodetect whether or not http is supported by the receiver and fallback to telnet (supported by all networked AVRs) if it doesn't.

**Comment by thexperiments** [comment]
Sounds great, looking forward to use it.

2016-04-14 12:16 GMT+02:00 Marcus Wittig notifications@github.com:

**Comment by mwittig** [comment]
Released. See also https://forum.pimatic.org/topic/1145/new-plugin-for-denon-marantz-avrs

A ZonePresenceDevice will be added with the next release. 

I am closing this issue now. Please re-open if related issues arise or you wish to follow-up. Any suggestions & feedback are welcome!
